version: '3'

services:
  django_api:
    build:
      context: ./django_room_booking_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./django_room_booking_api:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dev_secret_key
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django_api
    restart: unless-stopped 