version: '3'

services:
  django_api:
    build:
      context: ./django_room_booking_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./django_room_booking_api:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dev_secret_key
    restart: unless-stopped

  web:
    image: node:16-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    depends_on:
      - django_api
    restart: unless-stopped 