version: '3'

services:
  api:
    build:
      context: ./django_room_booking_api
      dockerfile: Dockerfile
    restart: always
    environment:
      - DEBUG=0
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DOMAIN},www.${DOMAIN}
    expose:
      - "8000"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    environment:
      - REACT_APP_API_URL=${API_URL}
    expose:
      - "80"
    depends_on:
      - api
      
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
      - api
    restart: always
    
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@${DOMAIN} --agree-tos --no-eff-email -d ${DOMAIN} -d www.${DOMAIN}
    depends_on:
      - nginx 